### ISSUE TITLE
Update to the data recording functionality

### ISSUE THREAD

**Issue by huanghuayh** [pocmo/SensorDashboard#12]
Currently, the mobile end revives only one type of sensor data at a time. However, when recording data into files, it is expected that all types sensor data being recorded at the same time. 

To achieve this goal, I plan to implement a switch function to either turn on or turn off the sensor filter. When the data record button is pushed, the sensor filter will be disabled. When the stop button is pushed, the sensor filter will be enabled again.

**Comment by RicardoTrindade** [comment]
I'd really like to see that done, as I'm trying to get data from both the accelerometer and gyroscope to perform some sensor fusion algorithms

**Comment by huanghuayh** [comment]
Sure, I have implement that in the following way:
1. A pair of buttons start and stop are added to the mobile module.
2. When the start button is pushed, a message is sent to the wear side, which turns on the sensor filter.
3. the sensor filter is implemented using a member variable "is_filter_on" in the DeviceClient class. The corresponding code is attached. 
4. Currently, when the sensor filter is turned off, all data collected will be recorded to the folder /sdcard/sensor_data. I think you can pick the accelerator and gyroscope there.

![image](https://cloud.githubusercontent.com/assets/3975954/8703580/efcb999e-2aeb-11e5-8a80-f78ce780195b.png)

**Comment by RicardoTrindade** [comment]
Wow, it looks nice, can you send the whole code to
ricardo.trindade743@gmail.com?
Thanks in advance!
