### ISSUE TITLE
Always Waiting

### ISSUE THREAD

**Issue by moshih** [pocmo/SensorDashboard#14]
My phone sometimes doesn't change from the "waiting for sensor input from a wearable," despite having a moto 360 hooked up to it.

**Comment by RicardoTrindade** [comment]
When that happens to me, I usually go back to the home menu and start the app again

**Comment by moshih** [comment]
Is there a way to increase the polling rate? Especially if I only want to get one set of information (such as the Accelerometer)?

**Comment by RicardoTrindade** [comment]
You have to change it in SensorService, you can change to SensorManager.SENSOR_DELAY_FASTEST or any other option, you can also change to a known sampling frequency in microssecends (check the android sensor documentation for more info)

**Comment by thebino** [comment]
@moshih please keep in Mind:

> We are throttling sending sensor data for the currently visible sensor on the phone (faster) and 
> all other sensors (slower) here:
> https://github.com/pocmo/SensorDashboard/blob/master/wear/src/main/java/com/github/pocmo/sensordashboard/DeviceClient.java#L64

**Comment by moshih** [comment]
OH, thank you so much, I was noticing that there was always a 3 second gap.
