### ISSUE TITLE
About communication

### ISSUE THREAD

**Issue by frankliang610** [pocmo/SensorDashboard#15]
I imported  the project into Android Studio, and ran from it.It started from beginning screen on my tablet Nexus 7, then stopped there.'waiting for sensor input from wearable.." I used the repository sumitted on July 24, 2015. I've also tried other repositories, they ended there as the same. However, the one I downloaded from Google App Store, it could work well, I can get the sensors measuring screen,  though it refuses to work from time to time. I am totally a new starter for application development, so I don't know how to deal with it. Could you help me with that? Thank you.  
Here are the devices I am using. 
mobile: Nexus 7
wear: Sony SmartWatch 3

**Comment by vwiedemann** [comment]
Edit: I just found the solution here
https://github.com/pocmo/SensorDashboard/issues/5
After deploying the app to the smartwatch and the phone it worked :)

**Comment by thebino** [comment]
@frankliang610 sorry for not answering your question, it got lost in my inbox.
See the answer @vwiedemann found in #5. You have to deploy the wearable app on the watch first, then (deploy &) start the app on the bounded smartphone and everything should work fine.

You can switch between the applications directly inside android studio:
<img width="172" alt="screen shot 2017-01-05 at 11 43 40" src="https://cloud.githubusercontent.com/assets/841681/21677840/3bc4d618-d33c-11e6-85da-7ba07cde837c.png">
