### ISSUE TITLE
The app does export only accelerometer data?

### ISSUE THREAD

**Issue by AttilioCapocchiani** [pocmo/SensorDashboard#16]
When I export data in csv it only exports accelerometer (I suppose it's accelerometer because I can read "acc" in the line). How can I export other sensors data?

**Comment by thebino** [comment]
This code was the result of a hackathon. I suggest you to create an enum for datasources and iterate through it. Consider that the data visualisation has to fit for every datatype.
While a line-graph is excellent for most graphs, it isn't useful for heartbeat or steps.

**Comment by AttilioCapocchiani** [comment]
I discovered that the class who saves data in the database in SensorFragment.java. How can I take data from other sensors? I understood that it saves data in `onSensorUpdatedEvent(SensorUpdatedEvent event)` when `event.getSensor().getId() == this.sensor.getId()`. I don't understand how to save data taken by all sensors. Where should I write the code?

**Comment by dbonsu7** [comment]
"When I export data in csv it only exports accelerometer (I suppose it's accelerometer because I can read "acc" in the line). How can I export other sensors data?"Same issue as Attilio.(i didn't really understand your response to him). Furthermore is there any documentation to tell you what the data values(columns in a csv file) and correspond to? Thanks

**Comment by RicardoTrindade** [comment]
Hey there dbonsu I suggest that you create a listener for all the sensors and keep storing values in arraylists and then write them to csv files. You can take a look at my code in https://github.com/RicardoTrindade/NightRecording/tree/master/NightRecording and see how I do it. The code is really similar to this app

**Comment by ruthot** [comment]
Have you solved this issue? I have the same problem.

**Comment by RicardoTrindade** [comment]
Take a look at my previous comment ruthot

**Comment by thebino** [comment]
@AttilioCapocchiani in SensorFragment only the currently selected sensor (viewpager page) is recorded. To record all sensor data you should write them to database inside the SensorReceiverService.
