### ISSUE TITLE
Bluetooth RSSI feature

### ISSUE THREAD

**Issue by lhjohn** [pocmo/SensorDashboard#17]
Hi,

is it possible to also receive the RSSI data of the Bluetooth connection between the Android Wear and a handheld? For instance by means of `readRemoteRSSI()`? I believe that the packets send should somehow hold this information, however, how can I read it out?

lhjohn

**Comment by pocmo** [comment]
We do not handle the bluetooth connection ourselves. This is all done by the Google Play Services that we are relying on. So I assume there's no direct way to access this data.
