### ISSUE TITLE
Could not detect heart rate sensor 

### ISSUE THREAD

**Issue by aekanman** [pocmo/SensorDashboard#18]
Using a huawei watch with all watch, mobile device and android studio's latest versions, I was never able to get the heart rate sensor working. Debugged the code for a while, all permissions are on, heart rate sensor always gets null for some weird reason and accelerometer, gyroscope, pressure and step counter are always on even when I comment out the listener lines.

**Comment by thebino** [comment]
Hi @aekanman, I checked this issue today and fixed it.
To prevent battery drain we added a periodically measuring with the heart rate sensor, the time we choose was to short in most cases, but now it is working with Huawei watches.
![screenshot_20170105-155848](https://cloud.githubusercontent.com/assets/841681/21686048/27f8ead4-d364-11e6-80d1-77e496c4cb21.png)
