### ISSUE TITLE
logging sensor data on the smart watch

### ISSUE THREAD

**Issue by morangad** [pocmo/SensorDashboard#20]
For a project I'm working on I need to log gyro and acc data **on the android smart watch** (few seconds) at about 100Hz, is it possible with the "Sensor Dashboard" app ?

**Comment by thebino** [comment]
@morangad sorry for the late answer. All sensor data are collected on the wearable and send to the bound smartphone where it is logged in the SensorReceiverService. If you want to log the events separately you can do this 

- on the watch in SensorService#onSensorChanged(SensorEvent event)
- on the smartphone in SensorReceiverService#unpackSensorData(int sensorType, DataMap dataMap)
