### ISSUE TITLE
Sensor Data normalization

### ISSUE THREAD

**Issue by pantos06** [pocmo/SensorDashboard#21]
Hi! I don't understand the normalization of collected data in your project. Could you explain me how that work please?

**Comment by nandi9** [comment]
I am not getting correct epoch time in CSV file. Could anyone help?

**Comment by thebino** [comment]
@pantos06 which part exactly should be explained? On mobile we draw the real data, there isn't any high pass neither lowpass filter active right now.

**Comment by nandi9** [comment]
Sir, can't we get the data of two sensors at a time in CSV?

**Comment by thebino** [comment]
@nandi9 you've to adjust the source code by yourself. This project is only a skeleton to work with wearable sensors
