### ISSUE TITLE
Cover most of the smart watches out there

### ISSUE THREAD

**Issue by ghost** [pocmo/SensorDashboard#24]
Hi folks, this may be a silly question, but I'm new developing for wearable devices, and Wikipedia says that there is Smart Watches with Android Wear 2.0 OS and Smart Watches with Android OS by itself.
[https://en.wikipedia.org/wiki/Smartwatch#Operating_systems](https://en.wikipedia.org/wiki/Smartwatch#Operating_systems)
So my question is, after Google released Android Wear OS there is no more Android OS Smart Watches on the market? only Smart Watches with Android Wear OS? should i worry about Smart Watches running Android OS nowadyas? because I'm developing an APP and I'm trying to cover most of the Android Smart Watches out there, so i thought in using Android Wear 2.0 SDK and Tizen SDK for Samsung Smart Watches, but now i don't know if i should worry about Smart Watches running Android OS, should I? if that's the case what would be the SDK for it? thank you very much for your help guys :)
Oh and for IOS, watch OS and Tizen OS will cover most of the smart watches for Iphones out there? thanks

**Comment by thebino** [comment]
Hi @orlandoabreu221,
this project was only a developer tool to visualize sensor data on android wear 1.
As you can see, the code doesn't got any updates in the past 2-3 years. We're not a community for generell wearable questions, but I'm sure you're a smart guy and find the answers on twitter or google+
Personally I would recommend, to wait for the google I/O this year. After announcing a new name (Wear OS by Google) they will definitely update their portfolio again.
