### ISSUE TITLE
Can not run on the watch (wear)

### ISSUE THREAD

**Issue by silvermind20** [pocmo/SensorDashboard#25]
I read through the closed issues and followed all the instructions for running the app on my watch. I don not know if there is a technical difference than "run" and "deploy" the app on the watch. If not, that's what I did. It builds and installs with no problem, but it does not open up at all. Run terminal says: Waiting for process to come online...
Timed out waiting for process to appear on compal-runway-  
I can not find the app in the list of my app but if I go to Settings -> App info -> then I can see the app is listed there and I have options like uninstall, force stop, permissions, etc. 
Could yo help me how I can do this?

P.S. I tried to change the build.gradle of the wear to a similar settings (aka sdk versions & stuff) of another wear app that I have and is working on my phone and that didn't help.

The app on the phone does build, install and run install totally normal, just waits for sensor info.

**Comment by thebino** [comment]
The app hasn't been maintained since 3 years, but I just build and deployed both apps (mobile and wear) on the respective devices and it is still working.
Did you build both apps?

mobile
`./gradlew mobile:assembleDebug`
`adb install -s <SERIAL_OF_MOBILE_DEVICE> mobile/build/output/apk/mobile-debug.apk`

wear
`./gradlew wear:assembleDebug`
`adb install -s <SERIAL_OF_WEARABLE> wear/build/output/apk/mobile-debug.apk`

To deploy on the wearable, you need to connect it via bluetooth or wifi.
https://developer.android.com/training/wearables/apps/debugging#usb-debugging

**Comment by silvermind20** [comment]
Thanks. I started the to deploy on wear first (has been suggested in other reported issues to install wear 1st). Gradlew finished with no error but when I tried running adb install command on my connected watch, I got this error:
Performing Streamed Install
adb: failed to stat wear/build/output/apk/mobile-debug.apk: No such file or directory

Also, why deploying "mobile-debug.apk" for both wear and mobile? 

Same error when deploying on phone:
Performing Streamed Install
adb: failed to stat mobile/build/output/apk/mobile-debug.apk: No such file or directory

**Comment by silvermind20** [comment]
Alright, I figured it out. 
1st, my path is not right, so I checked my correct apk path in my project files and then run the adb install. (probably becuz of updated gradle, I'm guessing)
2nd: then I faced another error of: java.lang.IllegalArgumentException: New installs into ASEC containers no longer supported .......
So, I found out that when you run the install command with "-s" you would instruct pm to explicitly install to the sdcard. To solve this, have to run it as:
adb install -f wear/build/outputs/apk/debug/wear-debug.apk

I finally got the success message on both devices. But it is still the same as before: phone is installed correctly & upon open, is waiting to recieved Sensor data but app does not open on the watch. I can not see it in my app lists but I can see it listed under Settings -> Apps info

**Comment by silvermind20** [comment]
Solved my issue by adding the codes below:
1) onCreate() in SensorService.java:
`if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O)
            startMyOwnForeground(this);
        else
            startForeground(101, new Notification());`

2) Add this method below that:
`@RequiresApi(api = Build.VERSION_CODES.O)
    private void startMyOwnForeground(Context context){
        String NOTIFICATION_CHANNEL_ID = "com.github.pocmo.sensordashboard";
        String channelName = "My Background Service";
        NotificationChannel chan = new NotificationChannel(NOTIFICATION_CHANNEL_ID, channelName, NotificationManager.IMPORTANCE_NONE);
        chan.setLightColor(Color.BLUE);
        chan.setLockscreenVisibility(Notification.VISIBILITY_PRIVATE);
        NotificationManager manager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
        assert manager != null;
        manager.createNotificationChannel(chan);

        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(context, NOTIFICATION_CHANNEL_ID);
        Notification notification = notificationBuilder.setOngoing(true)
                .setSmallIcon(R.drawable.icon_1)
                .setContentTitle("App is running in background")
                .setPriority(NotificationManager.IMPORTANCE_MIN)
                .setCategory(Notification.CATEGORY_SERVICE)
                .build();
        startForeground(2, notification);
    }`
3) Add this in Wear Manifest.xml:
`<uses-permission android:name="android.permission.FOREGROUND_SERVICE" />`

Explanation: once I upgraded my SDK, all these errors occurred. When using android services, it can not run in background if you are using Android 8.0 (API level 26) or higher and has to get permission for ForegroundServices and implement channel notification.
Read more about it [here](https://developer.android.com/training/notify-user/channels).
