### ISSUE TITLE
Needed some more explanation regarding sensor dashboard application.

### ISSUE THREAD

**Issue by Sabari-Karthik3** [pocmo/SensorDashboard#8]
I have gone through the project but am running wear application in emulator,so that am not able to get the service notifications from wear to mobile.please provide demo screenshots for reference.It will helps others too alot.And am dont know where to mention this comment,so only I have added this in issue block.

**Comment by thebino** [comment]
you have to pair your emulator to a real device. See official documentation for this step:
https://developer.android.com/training/wearables/apps/creating.html#SetupEmulator
![platinaldz22dbino05282015140053](https://cloud.githubusercontent.com/assets/841681/7859515/1068b0f8-0542-11e5-8492-4a73117c274f.png)

**Comment by Sabari-Karthik3** [comment]
yeap.I have paired my real mobile device to emulator and in that am not getting any changes in the mobile this is what am getting after running the application in mobile and as well as wear emulator.
![screenshot_2015-05-29-12-10-23](https://cloud.githubusercontent.com/assets/6196136/7877689/e7003b9a-05fb-11e5-9734-049fcb24a5fc.png)

**Comment by thebino** [comment]
Sorry, I didn't noticed: Emulators don't have any sensor!
You will see this in your logcat:

```
No Heartrate Sensor found
Samsungs Heartrate Sensor not found
No Light Sensor found
No Linear Acceleration Sensor found
No uncalibrated Magnetic Field Sensor found
No Pressure Sensor found
No Humidity Sensor found
No Rotation Vector Sensor found
No Significant Motion Sensor found
No Step Counter Sensor found
No Step Detector Sensor found
```
