### ISSUE TITLE
Frequent crash due to UI

### ISSUE THREAD

**Issue by huanghuayh** [pocmo/SensorDashboard#9]
When the number of sensors are too large, the ui will crash. To fix this problem, we need to take care of both the number of colors and number of views.

**Comment by huanghuayh** [comment]
I have tried to fix this problem by doing what follows: 
change  private boolean[] drawSensors = new boolean[6];
to  private boolean[] drawSensors = new boolean[20];

and use an if-else statement to handle the case when the number of sensors is larger than 9

**Comment by thebino** [comment]
fixed
